import "~/styles/tailwind.css";
import { NavBar, SearchBar } from "~/components";
import { getMovies, Providers } from "~/utils";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { use } from "react";
import BlobMouseEffect from "~/hyezo/BlobMouseEffect";
import Image from "next/image";
import Link from "next/link";

const font = Nunito({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "To Each Own Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  const movies = use(getMovies());

  return (
    <html lang="en" className={font.className}>
      <body draggable={false}>
        <BlobMouseEffect />
        <header className="mx-auto flex max-w-7xl items-center justify-center gap-10 border-b border-gray-600 px-10 py-4">
          <div className="flex-grow-0">
            <Link href="/" className="">
              <Image src="/remove.png" alt="logo" width={70} height={70} />
            </Link>
          </div>
          <div className="flex flex-grow justify-center">
            <SearchBar movies={movies} />
          </div>
        </header>
        <main className="mx-auto flex max-w-7xl pt-2 sm:flex-col sm:items-center md:flex-row md:items-start">
          <Providers movies={movies}>
            <NavBar className="sticky top-6 m-4 min-w-[12rem] rounded-2xl border border-gray-600 sm:hidden md:block" />
            <section className="flex-grow p-4">{children}</section>
          </Providers>
        </main>
      </body>
    </html>
  );
}
