import { NavBar, SearchBar } from "@/components/index";
import { getMovies, Providers } from "@/utils/index";
import "hyezo/ui/styles.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { use } from "react";
import "./styles/tailwind.css";

const font = Nunito({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "To Each Own Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  const movies = use(getMovies());

  return (
    <html lang="en" className={font.className}>
      <body>
        <header className="flex items-center justify-center border-b p-4">
          <SearchBar movies={movies} />
        </header>
        <main className="flex">
          <nav className="m-4 max-w-xs rounded-2xl border p-4">
            <NavBar className="flex flex-col gap-4" />
          </nav>
          <Providers movies={movies}>
            <section className="p-4">{children}</section>
          </Providers>
        </main>
      </body>
    </html>
  );
}
